{{- if .Values.replicaCount }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "quantora-chain.fullname" . }}-validator
spec:
  serviceName: "validator"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "quantora-chain.name" . }}-validator
  template:
    metadata:
      labels:
        app: {{ include "quantora-chain.name" . }}-validator
    spec:
      containers:
      - name: quantora-node
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - --chain=/etc/quantora/genesis.json
        - --validator
        - --bootnodes={{ .Values.bootnodes }}
        - --rpc-port={{ .Values.rpc.port }}
        - --p2p-port={{ .Values.p2p.port }}
        - --telemetry-url={{ .Values.telemetry.url }} 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/quantora
        - name: genesis
          mountPath: /etc/quantora
      volumes:
      - name: genesis
        configMap:
          name: quantora-genesis
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
{{- end }}