[workspace]
members = [
    "exchange",
    "blockchain/core",
    "blockchain/api",
    "indexer"
]
resolver = "2"

# Added by script:
sqlx = { version = "0.7", features = ["postgres"], default-features = false }
