name: Internal Asset Inventory & Tiering

on:
  schedule:
    - cron: "0 8 * * 0"

jobs:
  asset-inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Discover internal assets
        run: python scripts/discover_assets.py --scope internal --output assets.json
      - name: Tier/risk-rank assets
        run: python scripts/tier_assets.py --input assets.json --output asset_tiers.json
      - name: Upload asset tier report
        uses: actions/upload-artifact@v4
        with:
          name: asset-tier-report
          path: asset_tiers.json