name: Deploy Production

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'services/**'
      - 'infra/**'
      - 'platform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Set up Kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
      - name: Deploy to cluster
        run: |
          kubectl apply -f infra/k8s/
          kubectl rollout status deployment/quantora-platform --timeout=5m
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "🚀 Quantora platform deployed to production by ${{ github.actor }}."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}