name: Human-in-the-Loop Security Review

on:
  pull_request:
    branches: [main, develop]

jobs:
  security-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Automated risk summarization
        run: python scripts/risk_summary.py --pr ${{ github.event.number }} --output risk.txt
      - name: Require manual review for flagged risks
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Manual security review required: see risk.txt"
            })