name: Container Image Secrets Scan

on:
  push:
    branches: [main, develop]
    paths:
      - 'Dockerfile'
      - 'services/**'

jobs:
  secretscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t quantora-app:${{ github.sha }} .
      - name: Scan for secrets in image
        uses: aquasecurity/trivy-action@v0.13.1
        with:
          image-ref: quantora-app:${{ github.sha }}
          scan-type: "secret"