name: Internal Bug Bounty and Vulnerability Reporting

on:
  workflow_dispatch:

jobs:
  bug-bounty:
    runs-on: ubuntu-latest
    steps:
      - name: Ingest internal vulnerability report
        run: python scripts/ingest_bug_report.py --input reports/internal_vuln_report.json --output bug_bounty_case.json
      - name: Notify internal bounty triage team
        run: python scripts/notify_bounty_team.py --input bug_bounty_case.json
      - name: Upload bounty workflow log (internal)
        uses: actions/upload-artifact@v4
        with:
          name: bug-bounty-log
          path: bug_bounty_case.json