name: Internal Analytics Pipeline Orchestration

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  analytics-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger analytics ETL pipeline
        run: python scripts/run_internal_analytics.py --config configs/analytics_pipeline.yaml --output analytics_report.json
      - name: Upload analytics report
        uses: actions/upload-artifact@v4
        with:
          name: analytics-report
          path: analytics_report.json