name: Internal Service Mesh Observability & Policy Enforcement

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  mesh-observability:
    runs-on: ubuntu-latest
    steps:
      - name: Collect mesh traffic/metrics
        run: python scripts/collect_mesh_metrics.py --namespace quantora-internal --output mesh_metrics.json
      - name: Enforce mesh policies
        run: python scripts/enforce_mesh_policies.py --input mesh_metrics.json --policy configs/mesh_policy.yaml --output mesh_policy_enforcement.json
      - name: Upload mesh observability report
        uses: actions/upload-artifact@v4
        with:
          name: mesh-observability
          path: mesh_policy_enforcement.json