name: Internal Secrets Discovery & Rotation

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  secrets-discovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Discover secrets in internal repos
        run: python scripts/secrets_discovery.py --repos services/internal_api/ --output secrets_found.json
      - name: Rotate discovered secrets
        run: python scripts/rotate_discovered_secrets.py --input secrets_found.json
      - name: Upload secrets rotation report
        uses: actions/upload-artifact@v4
        with:
          name: secrets-rotation-report
          path: secrets_found.json