name: Owner-Attested Annual Security Review

on:
  workflow_dispatch:

jobs:
  annual-security-review:
    runs-on: ubuntu-latest
    steps:
      - name: Compile all security controls and events
        run: python scripts/compile_security_controls.py --year 2025 --output annual_security_review.json
      - name: Owner review and digital sign-off
        run: python scripts/owner_sign_review.py --input annual_security_review.json --owner "Comfort Lindokuhle Mhaleni" --country "South Africa" --output annual_signed_review.json
      - name: Upload signed annual review
        uses: actions/upload-artifact@v4
        with:
          name: annual-owner-security-review
          path: annual_signed_review.json