name: Policy-as-Code

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'infra/**'
      - 'services/**'
      - 'platform/**'

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.46.0/conftest_0.46.0_Linux_x86_64.tar.gz
          tar xvf conftest_0.46.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin
      - name: Policy check
        run: |
          conftest test infra/k8s/*.yaml