version: "3"
services:
  backend:
    build: .
    ports: ["4001:4001"]
  frontend:
    image: node:20
    command: "npm run dev"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"