apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: audit-es
  namespace: logging
spec:
  serviceName: "audit-es"
  replicas: 3
  selector:
    matchLabels:
      app: audit-es
  template:
    metadata:
      labels:
        app: audit-es
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: audit-es-pvc