apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers/fluentd.pos
      tag kubernetes.*
      format json
    </source>
    <match kubernetes.**>
      @type copy
      <store>
        @type elasticsearch
        host siem.quantora.com
        port 9200
        logstash_format true
        logstash_prefix kubernetes
        logstash_dateformat %Y.%m.%d
      </store>
      <store>
        @type slack
        webhook_url "#{ENV['SIEM_ALERTS_WEBHOOK']}"
      </store>
    </match>