apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quantora-readonly
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quantora-readonly-binding
subjects:
  - kind: ServiceAccount
    name: quantora-app
    namespace: quantora
roleRef:
  kind: ClusterRole
  name: quantora-readonly
  apiGroup: rbac.authorization.k8s.io