apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quantora-app-rb
  namespace: quantora
subjects:
  - kind: ServiceAccount
    name: quantora-app
    namespace: quantora
roleRef:
  kind: Role
  name: quantora-platform-role
  apiGroup: rbac.authorization.k8s.io