apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
  namespace: quantora
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault.quantora.com"
    roleName: "quantora-app"
    objects: |
      - objectName: "platform-api"
        secretPath: "secret/data/quantora/platform-api"
        secretKey: "JWT_SECRET"
      - objectName: "db-password"
        secretPath: "secret/data/quantora/db"
        secretKey: "password"