apiVersion: v1
kind: Secret
metadata:
  name: hsm-sealed-secret
  namespace: quantora
type: Opaque
data:
  api-key: <encrypted-by-hsm-tpm>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: quantora
spec:
  template:
    spec:
      containers:
        - name: api
          image: quantora/api:latest
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hsm-sealed-secret
                  key: api-key
      nodeSelector:
        node.kubernetes.io/hsm: "true"