[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
sqlx = { version = "0.7", features = ["postgres"], default-features = false }
