name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./exchange/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quantora-exchange-backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./exchange/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quantora-exchange-frontend:latest
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Update K8s deployment
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl set image deployment/exchange-backend exchange-backend=${{ secrets.DOCKERHUB_USERNAME }}/quantora-exchange-backend:latest
          kubectl set image deployment/exchange-frontend exchange-frontend=${{ secrets.DOCKERHUB_USERNAME }}/quantora-exchange-frontend:latest
          kubectl rollout status deployment/exchange-backend
          kubectl rollout status deployment/exchange-frontend